// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvicNJX9anCQBUCPG590jRsbAkDSoQxE',
    appId: '1:572512184967:web:217fd25299e0ef5bcd6622',
    messagingSenderId: '572512184967',
    projectId: 'flyin-3f90f',
    authDomain: 'flyin-3f90f.firebaseapp.com',
    storageBucket: 'flyin-3f90f.appspot.com',
    measurementId: 'G-1WCT9122P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vLmyaKZ3hoq5tDF3FrDXjAJD5qt6_cU',
    appId: '1:572512184967:android:02b4c4a869be6789cd6622',
    messagingSenderId: '572512184967',
    projectId: 'flyin-3f90f',
    storageBucket: 'flyin-3f90f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUcYwVXkYyTwQ1vyu-a2TNBDG6Wz_4YuI',
    appId: '1:572512184967:ios:d80f54a386b262b9cd6622',
    messagingSenderId: '572512184967',
    projectId: 'flyin-3f90f',
    storageBucket: 'flyin-3f90f.appspot.com',
    iosBundleId: 'com.example.flyin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUcYwVXkYyTwQ1vyu-a2TNBDG6Wz_4YuI',
    appId: '1:572512184967:ios:1593ebda007e88cccd6622',
    messagingSenderId: '572512184967',
    projectId: 'flyin-3f90f',
    storageBucket: 'flyin-3f90f.appspot.com',
    iosBundleId: 'com.example.flyin.RunnerTests',
  );
}
